version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.4.1-jessie-node
        environment:
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB:  rails_engine_2_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run:
        name: Configure Bundler
        command: |
          echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
          source $BASH_ENV
          gem install bundler
          bundle install
      - run:
        name: db setup
        command: |
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rake import:sales_engine
      - run:
        name: rspec testing
        command: |
          mkdir -p /tmp/test-results
          bundle exec rspec --profile 10 \
                          --format RspecJunitFormatter \
                          --out /tmp/test-results/rspec.xml \
                          --format progress \
                          $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: /tmp/test-results
